version: 2
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .git
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
    - whitespace
    # Additional auto-fixable linters
    - godot          # Ensures comments end with periods
    - nlreturn       # Adds newlines before returns/branches
    - nolintlint     # Fixes malformed nolint directives
    - tagalign       # Aligns struct tags
    - usestdlibvars  # Uses stdlib constants instead of literals
    - copyloopvar    # Fixes loop variable copying issues
    - dupword        # Removes duplicate words
    - errorlint      # Fixes error wrapping issues
    - importas       # Enforces consistent import aliases
    - intrange       # Uses integer ranges in for loops
    - mirror         # Fixes bytes/strings usage patterns
    - perfsprint     # Replaces fmt.Sprintf with faster alternatives
  disable:
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
      - name: if-return
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code

  lll:
    line-length: 120  # Reduced for better readability and auto-wrapping

  staticcheck:
    checks: ["all"]

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 2
    min-occurrences: 3

  nakedret:
    max-func-lines: 30

  godot:
    scope: declarations
    exclude:
      - "^\\s*TODO"
      - "^\\s*FIXME"
    capital: false

  tagalign:
    align: false
    sort: true

  importas:
    no-unaliased: true
    alias:
      - pkg: github.com/stretchr/testify/assert
        alias: assert
      - pkg: github.com/stretchr/testify/require
        alias: require

  nlreturn:
    block-size: 2

  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true



issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - gocritic

    - path: examples/
      linters:
        - errcheck
        - gosec
        - gocritic

    - path: \.pb\.go
      linters:
        - all
    - path: compute/cpu_engine\.go
      linters:
        - gosec

  max-issues-per-linter: 50
  max-same-issues: 3
