// Experimental — this package is not yet wired into the main framework.
//
// Package regime provides Hidden Markov Model (HMM) based regime classification
// for time series data.
//
// The primary entry point is the HMM type, which models observable sequences as
// being generated by transitions between hidden states (regimes). Typical
// regimes include trending, mean-reverting, volatile, and crash states.
//
// Training uses the Baum-Welch algorithm (Expectation-Maximisation for HMMs):
//
//  1. Forward pass — compute forward probabilities α(t,i) = P(o₁…oₜ, sₜ=i).
//  2. Backward pass — compute backward probabilities β(t,i) = P(oₜ₊₁…oT | sₜ=i).
//  3. E-step — compute state occupation γ(t,i) and transition ξ(t,i,j) posteriors.
//  4. M-step — re-estimate initial, transition, and emission parameters.
//
// Decoding uses the Viterbi algorithm to find the most likely hidden state
// sequence given an observation sequence.
//
// Emissions are modelled as univariate Gaussians (one mean and variance per
// hidden state).
//
// (Stability: alpha)
package regime
