// Code generated by hand (protoc unavailable). DO NOT EDIT.
// source: serve/disaggregated/proto/disagg.proto

package disaggpb

// PreFillRequest is sent by the router to a prefill worker.
type PreFillRequest struct {
	RequestId    string  `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TokenIds     []int32 `protobuf:"varint,2,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`
	MaxNewTokens int32   `protobuf:"varint,3,opt,name=max_new_tokens,json=maxNewTokens,proto3" json:"max_new_tokens,omitempty"`
	Temperature  float32 `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
}

func (x *PreFillRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PreFillRequest) GetTokenIds() []int32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *PreFillRequest) GetMaxNewTokens() int32 {
	if x != nil {
		return x.MaxNewTokens
	}
	return 0
}

func (x *PreFillRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

// KVBlock carries a single key-value cache block for one layer.
type KVBlock struct {
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LayerIdx  int32  `protobuf:"varint,2,opt,name=layer_idx,json=layerIdx,proto3" json:"layer_idx,omitempty"`
	BlockIdx  int32  `protobuf:"varint,3,opt,name=block_idx,json=blockIdx,proto3" json:"block_idx,omitempty"`
	KData     []byte `protobuf:"bytes,4,opt,name=k_data,json=kData,proto3" json:"k_data,omitempty"`
	VData     []byte `protobuf:"bytes,5,opt,name=v_data,json=vData,proto3" json:"v_data,omitempty"`
}

func (x *KVBlock) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *KVBlock) GetLayerIdx() int32 {
	if x != nil {
		return x.LayerIdx
	}
	return 0
}

func (x *KVBlock) GetBlockIdx() int32 {
	if x != nil {
		return x.BlockIdx
	}
	return 0
}

func (x *KVBlock) GetKData() []byte {
	if x != nil {
		return x.KData
	}
	return nil
}

func (x *KVBlock) GetVData() []byte {
	if x != nil {
		return x.VData
	}
	return nil
}

// KVBlockStream wraps a KVBlock with a done flag for streaming.
type KVBlockStream struct {
	Block *KVBlock `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Done  bool     `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *KVBlockStream) GetBlock() *KVBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *KVBlockStream) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

// DecodeRequest is sent by the router to a decode worker.
type DecodeRequest struct {
	RequestId    string     `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	KvBlocks     []*KVBlock `protobuf:"bytes,2,rep,name=kv_blocks,json=kvBlocks,proto3" json:"kv_blocks,omitempty"`
	TokenIds     []int32    `protobuf:"varint,3,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`
	MaxNewTokens int32      `protobuf:"varint,4,opt,name=max_new_tokens,json=maxNewTokens,proto3" json:"max_new_tokens,omitempty"`
	Temperature  float32    `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
}

func (x *DecodeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DecodeRequest) GetKvBlocks() []*KVBlock {
	if x != nil {
		return x.KvBlocks
	}
	return nil
}

func (x *DecodeRequest) GetTokenIds() []int32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *DecodeRequest) GetMaxNewTokens() int32 {
	if x != nil {
		return x.MaxNewTokens
	}
	return 0
}

func (x *DecodeRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

// TokenStream is streamed back from a decode worker.
type TokenStream struct {
	RequestId    string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TokenId      int32  `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Done         bool   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	FinishReason string `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
}

func (x *TokenStream) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TokenStream) GetTokenId() int32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *TokenStream) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *TokenStream) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}
