// Code generated by hand (protoc unavailable). DO NOT EDIT.
// source: serve/disaggregated/proto/disagg.proto

package disaggpb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ---------------------------------------------------------------------------
// PrefillWorker
// ---------------------------------------------------------------------------

const PrefillWorker_Prefill_FullMethodName = "/disagg.PrefillWorker/Prefill"

// PrefillWorkerClient is the client API for PrefillWorker service.
type PrefillWorkerClient interface {
	Prefill(ctx context.Context, in *PreFillRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KVBlockStream], error)
}

type prefillWorkerClient struct {
	cc grpc.ClientConnInterface
}

// NewPrefillWorkerClient returns a new PrefillWorkerClient.
func NewPrefillWorkerClient(cc grpc.ClientConnInterface) PrefillWorkerClient {
	return &prefillWorkerClient{cc}
}

func (c *prefillWorkerClient) Prefill(ctx context.Context, in *PreFillRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KVBlockStream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PrefillWorker_ServiceDesc.Streams[0], PrefillWorker_Prefill_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PreFillRequest, KVBlockStream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// PrefillWorkerServer is the server API for PrefillWorker service.
type PrefillWorkerServer interface {
	Prefill(*PreFillRequest, grpc.ServerStreamingServer[KVBlockStream]) error
	mustEmbedUnimplementedPrefillWorkerServer()
}

// UnimplementedPrefillWorkerServer should be embedded to have forward compatible implementations.
type UnimplementedPrefillWorkerServer struct{}

func (UnimplementedPrefillWorkerServer) Prefill(*PreFillRequest, grpc.ServerStreamingServer[KVBlockStream]) error {
	return status.Errorf(codes.Unimplemented, "method Prefill not implemented")
}
func (UnimplementedPrefillWorkerServer) mustEmbedUnimplementedPrefillWorkerServer() {}

// UnsafePrefillWorkerServer may be embedded to opt out of forward compatibility.
type UnsafePrefillWorkerServer interface {
	mustEmbedUnimplementedPrefillWorkerServer()
}

func RegisterPrefillWorkerServer(s grpc.ServiceRegistrar, srv PrefillWorkerServer) {
	s.RegisterService(&PrefillWorker_ServiceDesc, srv)
}

func _PrefillWorker_Prefill_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PreFillRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrefillWorkerServer).Prefill(m, &grpc.GenericServerStream[PreFillRequest, KVBlockStream]{ServerStream: stream})
}

// PrefillWorker_ServiceDesc is the grpc.ServiceDesc for PrefillWorker service.
var PrefillWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "disagg.PrefillWorker",
	HandlerType: (*PrefillWorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Prefill",
			Handler:       _PrefillWorker_Prefill_Handler,
			ServerStreams:  true,
			ClientStreams:  false,
		},
	},
	Metadata: "serve/disaggregated/proto/disagg.proto",
}

// ---------------------------------------------------------------------------
// DecodeWorker
// ---------------------------------------------------------------------------

const DecodeWorker_Decode_FullMethodName = "/disagg.DecodeWorker/Decode"

// DecodeWorkerClient is the client API for DecodeWorker service.
type DecodeWorkerClient interface {
	Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenStream], error)
}

type decodeWorkerClient struct {
	cc grpc.ClientConnInterface
}

// NewDecodeWorkerClient returns a new DecodeWorkerClient.
func NewDecodeWorkerClient(cc grpc.ClientConnInterface) DecodeWorkerClient {
	return &decodeWorkerClient{cc}
}

func (c *decodeWorkerClient) Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenStream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DecodeWorker_ServiceDesc.Streams[0], DecodeWorker_Decode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DecodeRequest, TokenStream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// DecodeWorkerServer is the server API for DecodeWorker service.
type DecodeWorkerServer interface {
	Decode(*DecodeRequest, grpc.ServerStreamingServer[TokenStream]) error
	mustEmbedUnimplementedDecodeWorkerServer()
}

// UnimplementedDecodeWorkerServer should be embedded to have forward compatible implementations.
type UnimplementedDecodeWorkerServer struct{}

func (UnimplementedDecodeWorkerServer) Decode(*DecodeRequest, grpc.ServerStreamingServer[TokenStream]) error {
	return status.Errorf(codes.Unimplemented, "method Decode not implemented")
}
func (UnimplementedDecodeWorkerServer) mustEmbedUnimplementedDecodeWorkerServer() {}

// UnsafeDecodeWorkerServer may be embedded to opt out of forward compatibility.
type UnsafeDecodeWorkerServer interface {
	mustEmbedUnimplementedDecodeWorkerServer()
}

func RegisterDecodeWorkerServer(s grpc.ServiceRegistrar, srv DecodeWorkerServer) {
	s.RegisterService(&DecodeWorker_ServiceDesc, srv)
}

func _DecodeWorker_Decode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DecodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DecodeWorkerServer).Decode(m, &grpc.GenericServerStream[DecodeRequest, TokenStream]{ServerStream: stream})
}

// DecodeWorker_ServiceDesc is the grpc.ServiceDesc for DecodeWorker service.
var DecodeWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "disagg.DecodeWorker",
	HandlerType: (*DecodeWorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Decode",
			Handler:       _DecodeWorker_Decode_Handler,
			ServerStreams:  true,
			ClientStreams:  false,
		},
	},
	Metadata: "serve/disaggregated/proto/disagg.proto",
}
