// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: distributed/pb/coordinator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_distributed_pb_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_distributed_pb_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Peers         []string               `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_distributed_pb_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_distributed_pb_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorkerResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RegisterWorkerResponse) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

type UnregisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterWorkerRequest) Reset() {
	*x = UnregisterWorkerRequest{}
	mi := &file_distributed_pb_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterWorkerRequest) ProtoMessage() {}

func (x *UnregisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*UnregisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_distributed_pb_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type UnregisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterWorkerResponse) Reset() {
	*x = UnregisterWorkerResponse{}
	mi := &file_distributed_pb_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterWorkerResponse) ProtoMessage() {}

func (x *UnregisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*UnregisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_distributed_pb_coordinator_proto_rawDescGZIP(), []int{3}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_distributed_pb_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_distributed_pb_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_distributed_pb_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_distributed_pb_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StartCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCheckpointRequest) Reset() {
	*x = StartCheckpointRequest{}
	mi := &file_distributed_pb_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCheckpointRequest) ProtoMessage() {}

func (x *StartCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCheckpointRequest.ProtoReflect.Descriptor instead.
func (*StartCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_distributed_pb_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *StartCheckpointRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *StartCheckpointRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StartCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCheckpointResponse) Reset() {
	*x = StartCheckpointResponse{}
	mi := &file_distributed_pb_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCheckpointResponse) ProtoMessage() {}

func (x *StartCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCheckpointResponse.ProtoReflect.Descriptor instead.
func (*StartCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_distributed_pb_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *StartCheckpointResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type EndCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,3,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCheckpointRequest) Reset() {
	*x = EndCheckpointRequest{}
	mi := &file_distributed_pb_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCheckpointRequest) ProtoMessage() {}

func (x *EndCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCheckpointRequest.ProtoReflect.Descriptor instead.
func (*EndCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_distributed_pb_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *EndCheckpointRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *EndCheckpointRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EndCheckpointRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type EndCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCheckpointResponse) Reset() {
	*x = EndCheckpointResponse{}
	mi := &file_distributed_pb_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCheckpointResponse) ProtoMessage() {}

func (x *EndCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCheckpointResponse.ProtoReflect.Descriptor instead.
func (*EndCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_distributed_pb_coordinator_proto_rawDescGZIP(), []int{9}
}

var File_distributed_pb_coordinator_proto protoreflect.FileDescriptor

const file_distributed_pb_coordinator_proto_rawDesc = "" +
	"\n" +
	" distributed/pb/coordinator.proto\x12\vdistributed\"N\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"B\n" +
	"\x16RegisterWorkerResponse\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05peers\x18\x02 \x03(\tR\x05peers\"6\n" +
	"\x17UnregisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\x1a\n" +
	"\x18UnregisterWorkerResponse\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"+\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"B\n" +
	"\x16StartCheckpointRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\">\n" +
	"\x17StartCheckpointResponse\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\"n\n" +
	"\x14EndCheckpointRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12#\n" +
	"\rcheckpoint_id\x18\x03 \x01(\tR\fcheckpointId\"\x17\n" +
	"\x15EndCheckpointResponse2\xd5\x03\n" +
	"\vCoordinator\x12[\n" +
	"\x0eRegisterWorker\x12\".distributed.RegisterWorkerRequest\x1a#.distributed.RegisterWorkerResponse\"\x00\x12a\n" +
	"\x10UnregisterWorker\x12$.distributed.UnregisterWorkerRequest\x1a%.distributed.UnregisterWorkerResponse\"\x00\x12L\n" +
	"\tHeartbeat\x12\x1d.distributed.HeartbeatRequest\x1a\x1e.distributed.HeartbeatResponse\"\x00\x12^\n" +
	"\x0fStartCheckpoint\x12#.distributed.StartCheckpointRequest\x1a$.distributed.StartCheckpointResponse\"\x00\x12X\n" +
	"\rEndCheckpoint\x12!.distributed.EndCheckpointRequest\x1a\".distributed.EndCheckpointResponse\"\x00B)Z'github.com/zerfoo/zerfoo/distributed/pbb\x06proto3"

var (
	file_distributed_pb_coordinator_proto_rawDescOnce sync.Once
	file_distributed_pb_coordinator_proto_rawDescData []byte
)

func file_distributed_pb_coordinator_proto_rawDescGZIP() []byte {
	file_distributed_pb_coordinator_proto_rawDescOnce.Do(func() {
		file_distributed_pb_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distributed_pb_coordinator_proto_rawDesc), len(file_distributed_pb_coordinator_proto_rawDesc)))
	})
	return file_distributed_pb_coordinator_proto_rawDescData
}

var file_distributed_pb_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_distributed_pb_coordinator_proto_goTypes = []any{
	(*RegisterWorkerRequest)(nil),    // 0: distributed.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),   // 1: distributed.RegisterWorkerResponse
	(*UnregisterWorkerRequest)(nil),  // 2: distributed.UnregisterWorkerRequest
	(*UnregisterWorkerResponse)(nil), // 3: distributed.UnregisterWorkerResponse
	(*HeartbeatRequest)(nil),         // 4: distributed.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 5: distributed.HeartbeatResponse
	(*StartCheckpointRequest)(nil),   // 6: distributed.StartCheckpointRequest
	(*StartCheckpointResponse)(nil),  // 7: distributed.StartCheckpointResponse
	(*EndCheckpointRequest)(nil),     // 8: distributed.EndCheckpointRequest
	(*EndCheckpointResponse)(nil),    // 9: distributed.EndCheckpointResponse
}
var file_distributed_pb_coordinator_proto_depIdxs = []int32{
	0, // 0: distributed.Coordinator.RegisterWorker:input_type -> distributed.RegisterWorkerRequest
	2, // 1: distributed.Coordinator.UnregisterWorker:input_type -> distributed.UnregisterWorkerRequest
	4, // 2: distributed.Coordinator.Heartbeat:input_type -> distributed.HeartbeatRequest
	6, // 3: distributed.Coordinator.StartCheckpoint:input_type -> distributed.StartCheckpointRequest
	8, // 4: distributed.Coordinator.EndCheckpoint:input_type -> distributed.EndCheckpointRequest
	1, // 5: distributed.Coordinator.RegisterWorker:output_type -> distributed.RegisterWorkerResponse
	3, // 6: distributed.Coordinator.UnregisterWorker:output_type -> distributed.UnregisterWorkerResponse
	5, // 7: distributed.Coordinator.Heartbeat:output_type -> distributed.HeartbeatResponse
	7, // 8: distributed.Coordinator.StartCheckpoint:output_type -> distributed.StartCheckpointResponse
	9, // 9: distributed.Coordinator.EndCheckpoint:output_type -> distributed.EndCheckpointResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_distributed_pb_coordinator_proto_init() }
func file_distributed_pb_coordinator_proto_init() {
	if File_distributed_pb_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distributed_pb_coordinator_proto_rawDesc), len(file_distributed_pb_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distributed_pb_coordinator_proto_goTypes,
		DependencyIndexes: file_distributed_pb_coordinator_proto_depIdxs,
		MessageInfos:      file_distributed_pb_coordinator_proto_msgTypes,
	}.Build()
	File_distributed_pb_coordinator_proto = out.File
	file_distributed_pb_coordinator_proto_goTypes = nil
	file_distributed_pb_coordinator_proto_depIdxs = nil
}
