// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: distributed/pb/dist.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shape         []int32                `protobuf:"varint,1,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	Data          []float32              `protobuf:"fixed32,2,rep,packed,name=data,proto3" json:"data,omitempty"` // Using float32 for simplicity of transport
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tensor) Reset() {
	*x = Tensor{}
	mi := &file_distributed_pb_dist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tensor) ProtoMessage() {}

func (x *Tensor) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_dist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tensor.ProtoReflect.Descriptor instead.
func (*Tensor) Descriptor() ([]byte, []int) {
	return file_distributed_pb_dist_proto_rawDescGZIP(), []int{0}
}

func (x *Tensor) GetShape() []int32 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *Tensor) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type AllReduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tensor        *Tensor                `protobuf:"bytes,2,opt,name=tensor,proto3" json:"tensor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllReduceRequest) Reset() {
	*x = AllReduceRequest{}
	mi := &file_distributed_pb_dist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllReduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllReduceRequest) ProtoMessage() {}

func (x *AllReduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_dist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllReduceRequest.ProtoReflect.Descriptor instead.
func (*AllReduceRequest) Descriptor() ([]byte, []int) {
	return file_distributed_pb_dist_proto_rawDescGZIP(), []int{1}
}

func (x *AllReduceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AllReduceRequest) GetTensor() *Tensor {
	if x != nil {
		return x.Tensor
	}
	return nil
}

type AllReduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tensor        *Tensor                `protobuf:"bytes,2,opt,name=tensor,proto3" json:"tensor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllReduceResponse) Reset() {
	*x = AllReduceResponse{}
	mi := &file_distributed_pb_dist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllReduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllReduceResponse) ProtoMessage() {}

func (x *AllReduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_dist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllReduceResponse.ProtoReflect.Descriptor instead.
func (*AllReduceResponse) Descriptor() ([]byte, []int) {
	return file_distributed_pb_dist_proto_rawDescGZIP(), []int{2}
}

func (x *AllReduceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AllReduceResponse) GetTensor() *Tensor {
	if x != nil {
		return x.Tensor
	}
	return nil
}

type BarrierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarrierRequest) Reset() {
	*x = BarrierRequest{}
	mi := &file_distributed_pb_dist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarrierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarrierRequest) ProtoMessage() {}

func (x *BarrierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_dist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarrierRequest.ProtoReflect.Descriptor instead.
func (*BarrierRequest) Descriptor() ([]byte, []int) {
	return file_distributed_pb_dist_proto_rawDescGZIP(), []int{3}
}

func (x *BarrierRequest) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type BarrierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarrierResponse) Reset() {
	*x = BarrierResponse{}
	mi := &file_distributed_pb_dist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarrierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarrierResponse) ProtoMessage() {}

func (x *BarrierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_dist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarrierResponse.ProtoReflect.Descriptor instead.
func (*BarrierResponse) Descriptor() ([]byte, []int) {
	return file_distributed_pb_dist_proto_rawDescGZIP(), []int{4}
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tensor        *Tensor                `protobuf:"bytes,2,opt,name=tensor,proto3" json:"tensor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_distributed_pb_dist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_dist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_distributed_pb_dist_proto_rawDescGZIP(), []int{5}
}

func (x *BroadcastRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BroadcastRequest) GetTensor() *Tensor {
	if x != nil {
		return x.Tensor
	}
	return nil
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tensor        *Tensor                `protobuf:"bytes,1,opt,name=tensor,proto3" json:"tensor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_distributed_pb_dist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributed_pb_dist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_distributed_pb_dist_proto_rawDescGZIP(), []int{6}
}

func (x *BroadcastResponse) GetTensor() *Tensor {
	if x != nil {
		return x.Tensor
	}
	return nil
}

var File_distributed_pb_dist_proto protoreflect.FileDescriptor

const file_distributed_pb_dist_proto_rawDesc = "" +
	"\n" +
	"\x19distributed/pb/dist.proto\x12\vdistributed\"2\n" +
	"\x06Tensor\x12\x14\n" +
	"\x05shape\x18\x01 \x03(\x05R\x05shape\x12\x12\n" +
	"\x04data\x18\x02 \x03(\x02R\x04data\"S\n" +
	"\x10AllReduceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x06tensor\x18\x02 \x01(\v2\x13.distributed.TensorR\x06tensor\"T\n" +
	"\x11AllReduceResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x06tensor\x18\x02 \x01(\v2\x13.distributed.TensorR\x06tensor\"$\n" +
	"\x0eBarrierRequest\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\"\x11\n" +
	"\x0fBarrierResponse\"S\n" +
	"\x10BroadcastRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x06tensor\x18\x02 \x01(\v2\x13.distributed.TensorR\x06tensor\"@\n" +
	"\x11BroadcastResponse\x12+\n" +
	"\x06tensor\x18\x01 \x01(\v2\x13.distributed.TensorR\x06tensor2\xfc\x01\n" +
	"\x12DistributedService\x12P\n" +
	"\tAllReduce\x12\x1d.distributed.AllReduceRequest\x1a\x1e.distributed.AllReduceResponse\"\x00(\x010\x01\x12F\n" +
	"\aBarrier\x12\x1b.distributed.BarrierRequest\x1a\x1c.distributed.BarrierResponse\"\x00\x12L\n" +
	"\tBroadcast\x12\x1d.distributed.BroadcastRequest\x1a\x1e.distributed.BroadcastResponse\"\x00B)Z'github.com/zerfoo/zerfoo/distributed/pbb\x06proto3"

var (
	file_distributed_pb_dist_proto_rawDescOnce sync.Once
	file_distributed_pb_dist_proto_rawDescData []byte
)

func file_distributed_pb_dist_proto_rawDescGZIP() []byte {
	file_distributed_pb_dist_proto_rawDescOnce.Do(func() {
		file_distributed_pb_dist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distributed_pb_dist_proto_rawDesc), len(file_distributed_pb_dist_proto_rawDesc)))
	})
	return file_distributed_pb_dist_proto_rawDescData
}

var file_distributed_pb_dist_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_distributed_pb_dist_proto_goTypes = []any{
	(*Tensor)(nil),            // 0: distributed.Tensor
	(*AllReduceRequest)(nil),  // 1: distributed.AllReduceRequest
	(*AllReduceResponse)(nil), // 2: distributed.AllReduceResponse
	(*BarrierRequest)(nil),    // 3: distributed.BarrierRequest
	(*BarrierResponse)(nil),   // 4: distributed.BarrierResponse
	(*BroadcastRequest)(nil),  // 5: distributed.BroadcastRequest
	(*BroadcastResponse)(nil), // 6: distributed.BroadcastResponse
}
var file_distributed_pb_dist_proto_depIdxs = []int32{
	0, // 0: distributed.AllReduceRequest.tensor:type_name -> distributed.Tensor
	0, // 1: distributed.AllReduceResponse.tensor:type_name -> distributed.Tensor
	0, // 2: distributed.BroadcastRequest.tensor:type_name -> distributed.Tensor
	0, // 3: distributed.BroadcastResponse.tensor:type_name -> distributed.Tensor
	1, // 4: distributed.DistributedService.AllReduce:input_type -> distributed.AllReduceRequest
	3, // 5: distributed.DistributedService.Barrier:input_type -> distributed.BarrierRequest
	5, // 6: distributed.DistributedService.Broadcast:input_type -> distributed.BroadcastRequest
	2, // 7: distributed.DistributedService.AllReduce:output_type -> distributed.AllReduceResponse
	4, // 8: distributed.DistributedService.Barrier:output_type -> distributed.BarrierResponse
	6, // 9: distributed.DistributedService.Broadcast:output_type -> distributed.BroadcastResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_distributed_pb_dist_proto_init() }
func file_distributed_pb_dist_proto_init() {
	if File_distributed_pb_dist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distributed_pb_dist_proto_rawDesc), len(file_distributed_pb_dist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distributed_pb_dist_proto_goTypes,
		DependencyIndexes: file_distributed_pb_dist_proto_depIdxs,
		MessageInfos:      file_distributed_pb_dist_proto_msgTypes,
	}.Build()
	File_distributed_pb_dist_proto = out.File
	file_distributed_pb_dist_proto_goTypes = nil
	file_distributed_pb_dist_proto_depIdxs = nil
}
