package distributed

import (
	"fmt"
	"sync"
	"unsafe"

	"github.com/zerfoo/zerfoo/internal/cuda"
)

// NCCLComm wraps an NCCL communicator loaded via purego dlopen.
// Unlike internal/nccl (which uses CGo), this implementation has zero
// CGo overhead and does not require the cuda build tag.
type NCCLComm struct {
	handle  uintptr // ncclComm_t
	nRanks  int
	rank    int
	ncclLib *ncclLibrary
}

// ncclLibrary holds dlopen handles and resolved function pointers for NCCL.
type ncclLibrary struct {
	handle uintptr // dlopen handle for libnccl

	ncclGetUniqueId     uintptr
	ncclCommInitRank    uintptr
	ncclCommDestroy     uintptr
	ncclAllGather       uintptr
	ncclReduceScatter   uintptr
	ncclAllReduce       uintptr
	ncclGroupStart      uintptr
	ncclGroupEnd        uintptr
	ncclGetErrorString  uintptr
}

// NCCL data type constants (match ncclDataType_t enum).
const (
	ncclFloat32 = 7
	ncclFloat64 = 9
)

// NCCL reduce op constants (match ncclRedOp_t enum).
const (
	ncclOpSum = 0
)

// NCCL result codes.
const ncclSuccess = 0

// ncclUniqueIDSize is the size of ncclUniqueId (128 bytes in NCCL 2.x).
const ncclUniqueIDSize = 128

var (
	globalNCCL     *ncclLibrary
	globalNCCLOnce sync.Once
	globalNCCLErr  error
)

// ncclLibPaths lists the shared library names to try, in order.
var ncclLibPaths = []string{
	"libnccl.so.2",
	"libnccl.so",
	"libnccl.dylib",
}

// openNCCL loads libnccl via dlopen and resolves all required function pointers.
func openNCCL() (*ncclLibrary, error) {
	lib := &ncclLibrary{}

	var lastErr error
	for _, path := range ncclLibPaths {
		h, err := cuda.DlopenPath(path)
		if err == nil {
			lib.handle = h
			break
		}
		lastErr = err
	}
	if lib.handle == 0 {
		return nil, fmt.Errorf("nccl: dlopen libnccl failed: %v", lastErr)
	}

	type sym struct {
		name string
		ptr  *uintptr
	}
	syms := []sym{
		{"ncclGetUniqueId", &lib.ncclGetUniqueId},
		{"ncclCommInitRank", &lib.ncclCommInitRank},
		{"ncclCommDestroy", &lib.ncclCommDestroy},
		{"ncclAllGather", &lib.ncclAllGather},
		{"ncclReduceScatter", &lib.ncclReduceScatter},
		{"ncclAllReduce", &lib.ncclAllReduce},
		{"ncclGroupStart", &lib.ncclGroupStart},
		{"ncclGroupEnd", &lib.ncclGroupEnd},
		{"ncclGetErrorString", &lib.ncclGetErrorString},
	}
	for _, s := range syms {
		addr, err := cuda.Dlsym(lib.handle, s.name)
		if err != nil {
			return nil, fmt.Errorf("nccl: %v", err)
		}
		*s.ptr = addr
	}

	return lib, nil
}

// ncclLib returns the lazily-initialized global NCCL library.
func ncclLib() *ncclLibrary {
	globalNCCLOnce.Do(func() {
		globalNCCL, globalNCCLErr = openNCCL()
	})
	return globalNCCL
}

// IsNCCLAvailable checks if libnccl.so can be loaded via dlopen.
func IsNCCLAvailable() bool {
	return ncclLib() != nil
}

// NCCLCommInitRank initializes a communicator for rank in an nRanks-size group.
// The id parameter is a 128-byte unique ID that must be the same across all ranks
// (generated by NCCLGetUniqueID on one rank and distributed to others).
func NCCLCommInitRank(nRanks, rank int, id [ncclUniqueIDSize]byte) (*NCCLComm, error) {
	lib := ncclLib()
	if lib == nil {
		return nil, fmt.Errorf("nccl: library not available: %v", globalNCCLErr)
	}

	// ncclCommInitRank(ncclComm_t* comm, int nranks, ncclUniqueId commId, int rank)
	// ncclUniqueId is a struct of 128 bytes, passed by value in C ABI.
	// We pass a pointer to the id bytes and the comm output pointer.
	var commHandle uintptr
	ret := cuda.Ccall(lib.ncclCommInitRank,
		uintptr(unsafe.Pointer(&commHandle)),
		uintptr(nRanks),
		uintptr(unsafe.Pointer(&id[0])),
		uintptr(rank),
	)
	if ret != ncclSuccess {
		return nil, fmt.Errorf("ncclCommInitRank(nRanks=%d, rank=%d) failed: error %d", nRanks, rank, ret)
	}

	return &NCCLComm{
		handle:  commHandle,
		nRanks:  nRanks,
		rank:    rank,
		ncclLib: lib,
	}, nil
}

// NCCLGetUniqueID generates a new unique ID for communicator initialization.
// Exactly one rank should call this and distribute the result to all other ranks.
func NCCLGetUniqueID() ([ncclUniqueIDSize]byte, error) {
	var id [ncclUniqueIDSize]byte
	lib := ncclLib()
	if lib == nil {
		return id, fmt.Errorf("nccl: library not available: %v", globalNCCLErr)
	}

	ret := cuda.Ccall(lib.ncclGetUniqueId, uintptr(unsafe.Pointer(&id[0])))
	if ret != ncclSuccess {
		return id, fmt.Errorf("ncclGetUniqueId failed: error %d", ret)
	}
	return id, nil
}

// NCCLAllGather gathers sendbuf from all ranks into recvbuf.
// recvbuf must be nRanks * len(sendbuf) elements. The stream parameter
// is a cudaStream_t (use 0 for the default stream).
func NCCLAllGather(comm *NCCLComm, sendbuf, recvbuf unsafe.Pointer, sendcount int, stream uintptr) error {
	if comm == nil {
		return fmt.Errorf("ncclAllGather: nil communicator")
	}
	lib := comm.ncclLib

	// ncclAllGather(const void* sendbuff, void* recvbuff, size_t sendcount,
	//               ncclDataType_t datatype, ncclComm_t comm, cudaStream_t stream)
	ret := cuda.Ccall(lib.ncclAllGather,
		uintptr(sendbuf),
		uintptr(recvbuf),
		uintptr(sendcount),
		uintptr(ncclFloat32),
		comm.handle,
		stream,
	)
	if ret != ncclSuccess {
		return fmt.Errorf("ncclAllGather failed: error %d", ret)
	}
	return nil
}

// NCCLAllGatherFloat64 is like NCCLAllGather but for float64 data.
func NCCLAllGatherFloat64(comm *NCCLComm, sendbuf, recvbuf unsafe.Pointer, sendcount int, stream uintptr) error {
	if comm == nil {
		return fmt.Errorf("ncclAllGather: nil communicator")
	}
	lib := comm.ncclLib

	ret := cuda.Ccall(lib.ncclAllGather,
		uintptr(sendbuf),
		uintptr(recvbuf),
		uintptr(sendcount),
		uintptr(ncclFloat64),
		comm.handle,
		stream,
	)
	if ret != ncclSuccess {
		return fmt.Errorf("ncclAllGather (float64) failed: error %d", ret)
	}
	return nil
}

// NCCLReduceScatter reduces across ranks and scatters the result.
// recvbuf gets sendcount/nRanks elements per rank. The stream parameter
// is a cudaStream_t (use 0 for the default stream).
func NCCLReduceScatter(comm *NCCLComm, sendbuf, recvbuf unsafe.Pointer, recvcount int, stream uintptr) error {
	if comm == nil {
		return fmt.Errorf("ncclReduceScatter: nil communicator")
	}
	lib := comm.ncclLib

	// ncclReduceScatter(const void* sendbuff, void* recvbuff, size_t recvcount,
	//                    ncclDataType_t datatype, ncclRedOp_t op,
	//                    ncclComm_t comm, cudaStream_t stream)
	ret := cuda.Ccall(lib.ncclReduceScatter,
		uintptr(sendbuf),
		uintptr(recvbuf),
		uintptr(recvcount),
		uintptr(ncclFloat32),
		uintptr(ncclOpSum),
		comm.handle,
		stream,
	)
	if ret != ncclSuccess {
		return fmt.Errorf("ncclReduceScatter failed: error %d", ret)
	}
	return nil
}

// NCCLReduceScatterFloat64 is like NCCLReduceScatter but for float64 data.
func NCCLReduceScatterFloat64(comm *NCCLComm, sendbuf, recvbuf unsafe.Pointer, recvcount int, stream uintptr) error {
	if comm == nil {
		return fmt.Errorf("ncclReduceScatter: nil communicator")
	}
	lib := comm.ncclLib

	ret := cuda.Ccall(lib.ncclReduceScatter,
		uintptr(sendbuf),
		uintptr(recvbuf),
		uintptr(recvcount),
		uintptr(ncclFloat64),
		uintptr(ncclOpSum),
		comm.handle,
		stream,
	)
	if ret != ncclSuccess {
		return fmt.Errorf("ncclReduceScatter (float64) failed: error %d", ret)
	}
	return nil
}

// Destroy releases the communicator resources.
func (c *NCCLComm) Destroy() error {
	if c == nil || c.handle == 0 {
		return nil
	}
	lib := c.ncclLib

	ret := cuda.Ccall(lib.ncclCommDestroy, c.handle)
	if ret != ncclSuccess {
		return fmt.Errorf("ncclCommDestroy failed: error %d", ret)
	}
	c.handle = 0
	return nil
}

// Rank returns the rank of this communicator.
func (c *NCCLComm) Rank() int { return c.rank }

// NRanks returns the total number of ranks in this communicator.
func (c *NCCLComm) NRanks() int { return c.nRanks }
